version: '3'

services:
  cmsStrapi:
    image: node:18-alpine
    ports:
      - "1337:1337"
    volumes:
      - .:/home/strapi/app
      - node_modules:/home/strapi/app/node_modules
    working_dir: /home/strapi/app/
    command: sh -c "yarn install && yarn build && yarn start"
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
volumes:
  node_modules:
  db: